spring.application.name=bms-rest-jdbc

server.port=3131

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/book_db
spring.datasource.username = root
spring.datasource.password = root
